/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cheon_androidcameraapi_CameraPreview_SaveImageTask */

#ifndef _Included_com_example_cheon_androidcameraapi_CameraPreview_SaveImageTask
#define _Included_com_example_cheon_androidcameraapi_CameraPreview_SaveImageTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
